title: "docs.mmaxii.xyz"
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: "https://docs.mmaxii.xyz/"

permalink: pretty

# Customization
color_scheme: "xyz-main"
favicon_ico: "/assets/images/favicon.ico"

# aux_links:
#  "mmaxii.xyz":
#    - "https://mmaxii.xyz/"

callouts_level: loud # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false 

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false 
  profile: false 
  # ignore:
  #   envs: all
  
