title: "docs.mmaxii.xyz"
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

# Customization
color_scheme: "dark"
favicon_ico: "/assets/images/favicon.ico"

url: "https://mmaxii-xyz.github.io/docs"

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# Custom styles
sass:
  custom_css: _sass/custom/custom.scss
